'use client';
import {useEffect,useState} from 'react';
import brand from '../olympiad.module.css';
import s from './join.module.css';
type Invitation={team_name:string;captain_name:string;event_year:number};
async function request(body:Record<string,unknown>){const response=await fetch('/olympiad/api/roster-link',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to load your team.');return data;}
export default function JoinRoster({allowPreview=false}:{allowPreview?:boolean}){
 const [token,setToken]=useState(''),[team,setTeam]=useState<Invitation|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[example,setExample]=useState(false);
 useEffect(()=>{let active=true;const incoming=window.location.hash.slice(1);setToken(incoming);
  if(allowPreview && new URLSearchParams(window.location.search).get('preview')==='1'){setExample(true);setTeam({team_name:'Your business',captain_name:'Your captain',event_year:2027});setLoading(false);return;}
  if(!/^[a-f0-9]{64}$/.test(incoming)){setError('Ask your captain for their team’s roster link.');setLoading(false);return;}
  request({action:'details',token:incoming}).then(data=>{if(active)setTeam(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});
  return()=>{active=false;};},[allowPreview]);
 return <div className={`${brand.hub} ${s.page}`}><header className={s.header}><a href="https://scottsdaleolympiad.com"><img src="/olympiad/saguaros.png" alt="The Saguaros"/><span><small>THE SAGUAROS PRESENT</small><strong>OLYMPIAD <em>2027</em></strong></span></a></header><main className={s.main}>
 {loading?<p role="status">Opening your team invitation…</p>:saved?<section className={s.card} aria-labelledby="saved-heading"><span className={s.eyebrow}>YOU’RE ON THE ROSTER</span><h1 id="saved-heading">You’re in, teammate.</h1><p>Your details are saved to <strong>{team?.team_name}</strong>. Your captain and Olympiad organizers can see them for shirt planning and event updates.</p><div className={s.next}><strong>What happens next?</strong><ul><li>Your captain will coordinate your team.</li><li>Shirt details are saved—no extra spreadsheet.</li><li>Want to change something? Ask your captain.</li></ul></div><p className={s.fine}>Update preferences are recorded. Submitting this form does not send a message or start an email or SMS campaign.</p><a className={s.primary} href="https://scottsdaleolympiad.com/#guide">Get to know Olympiad →</a></section>:team?<section className={s.card} aria-labelledby="join-heading"><span className={s.eyebrow}>YOUR TEAM INVITATION</span>{example&&<p className={s.tldr}>Form preview · Saving is disabled. Real invitations show the captain and team name.</p>}<h1 id="join-heading">Join {team.team_name}.</h1><p><strong>{team.captain_name||'Your captain'}</strong> is inviting you to Olympiad {team.event_year}. Add your details so we can get your shirt ready and keep you informed about the event.</p><div className={s.tldr}><strong>About a minute.</strong> No account needed. Your details stay private to your captain and event organizers.</div>
 <form onSubmit={async event=>{event.preventDefault();if(busy||example)return;const f=new FormData(event.currentTarget);setBusy(true);setError('');try{await request({action:'join',token,first_name:f.get('first_name'),last_name:f.get('last_name'),email:f.get('email'),phone:f.get('phone'),shirt_size:f.get('shirt_size'),shirt_fit:f.get('shirt_fit'),consent:f.get('consent')==='on',email_updates:f.get('email_updates')==='on',sms_updates:f.get('sms_updates')==='on'});setSaved(true);window.scrollTo({top:0,behavior:'instant'});}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}}><fieldset disabled={busy}><legend className={s.legend}>Your contact and shirt details</legend><div className={s.grid}>
 <label>First name<input name="first_name" required maxLength={60} pattern=".*\S.*" autoComplete="given-name"/></label><label>Last name<input name="last_name" required maxLength={60} pattern=".*\S.*" autoComplete="family-name"/></label><label>Email<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><label>Phone number<input name="phone" type="tel" required maxLength={40} autoComplete="tel" inputMode="tel"/></label><label>Shirt fit<select name="shirt_fit" required defaultValue=""><option value="" disabled>Choose fit</option><option value="male">Male fit</option><option value="female">Female fit</option></select></label><label>Shirt size<select name="shirt_size" required defaultValue=""><option value="" disabled>Choose size</option>{['XS','S','M','L','XL','2XL','3XL'].map(size=><option key={size}>{size}</option>)}</select></label></div>
 <label className={s.check}><input type="checkbox" name="consent" required/><span>I agree to share these details with my team captain and Olympiad organizers for shirt planning and event updates.</span></label>
 <details className={s.preferences}><summary>Choose extra updates (optional)</summary><label className={s.check}><input type="checkbox" name="email_updates"/><span>I would like Olympiad email updates and fundraising tips. I can unsubscribe anytime.</span></label><label className={s.check}><input type="checkbox" name="sms_updates"/><span>I would like Olympiad event updates by text. Message frequency varies. Message and data rates may apply. Reply STOP to opt out or HELP for help. Optional; not required to participate.</span></label><p className={s.fine}>Questions? <a href="mailto:scaldwell@saguaros.com">Contact the event team.</a> These preferences will be used when campaign setup is ready.</p></details>
 {error&&<p className={s.error} role="alert">{error}</p>}<button className={s.primary} disabled={busy||example}>{busy?'Saving your details…':'Add me to the team'}</button><p className={s.fine}>Already on the roster? Ask your captain to update your existing entry. No payment is collected here.</p></fieldset></form></section>:<section className={s.card}><h1>Let’s find your team.</h1><p role="alert">{error}</p><a href="https://scottsdaleolympiad.com">Explore Olympiad →</a></section>}
 </main><footer className={s.footer}>Good people. Doing good for Arizona’s kids.</footer></div>;
}
