import type {Metadata} from 'next';
import Layout from '../olympiad/layout';
import brand from '../olympiad/olympiad.module.css';
import results from '../olympiad/data/results-2026.json';
import s from './companies.module.css';
export const metadata:Metadata={title:'Scottsdale’s corporate field day | Olympiad 2027',description:'A day of team building, friendly business competition and support for Arizona children’s charities.',robots:{index:false,follow:false}};
const contact='mailto:scaldwell@saguaros.com';
const talk=`${contact}?subject=${encodeURIComponent('Olympiad 2027 — 15-minute team conversation')}&body=${encodeURIComponent('Hi Sean,\n\nI would like to talk about bringing a team to Olympiad 2027.\n\nBusiness:\nMy name:\nGood times for a 15-minute conversation:\n\nThank you!')}`;
const packet=`${contact}?subject=${encodeURIComponent('Olympiad 2027 — team packet request')}&body=${encodeURIComponent('Hi Sean,\n\nPlease send me the Olympiad 2027 team packet.\n\nBusiness:\nMy name:\n\nThank you!')}`;
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2}).format(cents/100);
export default function CompaniesPage(){return <Layout><div className={`${brand.hub} ${s.page}`}>
 <a className={s.skip} href="#company-content">Skip to content</a>
 <div className={s.preview}>OUTREACH PREVIEW · OLYMPIAD 2027</div>
 <header className={s.header}><a className={s.brand} href="https://scottsdaleolympiad.com"><img src="/olympiad/saguaros.png" alt="The Saguaros"/><span><small>THE SAGUAROS PRESENT</small><strong>OLYMPIAD <em>2027</em></strong></span></a><a className={s.return} href="https://scottsdaleolympiad.com/#signin">Already have a team? Sign in →</a></header>
 <main id="company-content">
 <section className={s.hero}><div className={s.heroCopy}><span className={s.eyebrow}>OLYMPIAD 2027 · THE SAGUAROS</span><h1>Scottsdale’s<br/><em>corporate field day.</em></h1><h2 className={s.heroPromise}>Bring your team.<br/>Rally for a common cause.</h2><p>Bring colleagues together for field-style games, connect with local businesses and turn friendly competition into support for Arizona children’s charities.</p><div className={s.actions}><a className={brand.goldButton} href={talk}>Explore bringing a team →</a><a className={s.lightLink} href={packet}>Request the team packet ↗</a></div><small>Email Sean to arrange a 15-minute conversation. Start with your questions.</small><div className={s.eventLine}>Planned April 2027 · Scottsdale Stadium<br/><span>Exact date to be confirmed. Final event details will follow.</span></div></div><div className={s.heroImage} role="img" aria-label="Olympiad teams gathering on the field at Scottsdale Stadium"/></section>
 <section className={s.facts} aria-label="Participation at a glance"><div><strong>Team building</strong><span>Connect beyond the office</span></div><div><strong>Business connections</strong><span>Meet your local competition</span></div><div><strong>Community impact</strong><span>Rally for Arizona’s children</span></div></section>
 <section className={s.section}><div className={s.sectionIntro}><span className={s.eyebrow}>YOUR PEOPLE. YOUR BUSINESS. YOUR COMMUNITY.</span><h2>Team building with a purpose.</h2><p>For the small-business owner bringing a crew, the team lead planning a company outing, or the returning captain ready for another round.</p></div><div className={s.cards}><article><span>01</span><h3>Connect beyond the office.</h3><p>A field-style games day brings colleagues together around a shared challenge, away from the office.</p></article><article><span>02</span><h3>Make new business connections.</h3><p>Meet other local businesses through friendly competition. Industry fundraising leaders earn cups; game winners earn medals.</p></article><article><span>03</span><h3>Show up for Arizona’s kids.</h3><p>Teams participate in fundraising to support the Saguaros’ work with Arizona children’s charities. We’ll explain the full commitment in your team packet or conversation before registration.</p><a href="https://scottsdaleolympiad.com/#impact">Explore the charitable impact →</a></article></div></section>
 <section className={s.proof}><div><span className={s.eyebrow}>THE 2026 FOUNDATION</span><h2>{money(results.reportTotalCents)}</h2><p>Reported support in the treasurer’s final 2026 Olympiad Team Sales report.</p></div><div><strong>91 named team entries</strong><p>{money(results.teamTotalCents)} credited to teams. The report groups team entries into seven categories.</p><details><summary>Understand the historical figures</summary><p>Accrual basis for {results.reportPeriod}, generated {results.reportGenerated}. This is reported support, not a statement of cash collected. The report also includes {money(results.unassignedCents)} “Not Specified” and {money(results.memberTotalCents)} active-member totals. Named entries are fundraising records, not a verified attendance count. These figures describe 2026 fundraising.</p></details><a href="https://scottsdaleolympiad.com/#leaderboard">Explore the 2026 results →</a></div></section>
 <section className={s.section}><div className={s.sectionIntro}><span className={s.eyebrow}>A SIMPLE START</span><h2>From curious to captain.<br/>One simple step at a time.</h2></div><ol className={s.steps}><li><strong>Let’s talk.</strong><p>Start with a 15-minute conversation or request the team packet. Get the format, commitment and your questions answered.</p></li><li><strong>Choose a captain.</strong><p>When you’re ready, choose a captain and register your business in the Olympiad hub. Your roster can come later.</p></li><li><strong>Get ready together.</strong><p>Add your roster, shirt sizes and logo. Use the hub for fundraising guidance, team progress and event updates.</p></li></ol><p className={s.note}>The hub is currently in early access. A conversation or packet request does not register a team or require a payment.</p></section>
 <section className={s.questions}><h2>A few things to know.</h2><details><summary>Is this for businesses like ours?</summary><p>Olympiad brings together businesses across industries. A captain represents your business and helps bring colleagues together. We’ll help you understand the team format and full participation commitment before registration.</p></details><details><summary>What does participation involve?</summary><p>Teams take part in fundraising for Arizona children’s charities. The 2027 participation and fundraising commitment is to be confirmed; we’ll explain it in the requested team packet or a conversation before registration. We’ll also walk through the support and fundraising options available to your team.</p><a href="https://scottsdaleolympiad.com/#fundraising">See the fundraising options →</a></details><details><summary>We’ve participated before. What’s changing?</summary><p>The new Olympiad hub brings team registration, roster and shirt details, your business logo, fundraising visibility and updates into one place.</p></details><details><summary>When is it?</summary><p>Planned April 2027 at Scottsdale Stadium. The exact date is to be confirmed; final event-day details will follow.</p></details></section>
 <section className={s.close}><span className={s.eyebrow}>LET’S FIND YOUR PLACE ON THE FIELD</span><h2>Curious? That’s enough to start.</h2><p>We’ll answer your questions and help you decide whether Olympiad is a fit for your business.</p><div className={s.actions}><a className={brand.goldButton} href={talk}>Explore bringing a team →</a><a className={s.lightLink} href={packet}>Request the team packet ↗</a></div><small>Both buttons open an email to the chairman. Packet requests are handled personally.</small></section>
 </main><footer className={s.footer}><strong>THE SAGUAROS</strong><span>Good people. Doing good for Arizona’s kids.</span><a href="https://scottsdaleolympiad.com">Explore Olympiad →</a></footer>
 </div></Layout>}
