'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import styles from './organizer.module.css';
type Contact={email:string;tags:string[];pending:boolean;last_synced_at:string|null;last_result:string|null;last_error:string|null};
const label=(result:string|null)=>result==='synced'?'Campaign groups synced':result==='missing_contact'?'Not in Mailchimp · subscription needed':result?.startsWith('suppressed_')?`Excluded · ${result.slice(11)}`:'Not synced yet';
export default function AudienceSync(){
 const [contacts,setContacts]=useState<Contact[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const running=useRef(false),mounted=useRef(true);
 const load=useCallback(async()=>{const r=await fetch('/olympiad/api/audience',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);if(mounted.current)setContacts(d.contacts);return d;},[]);
 const sync=useCallback(async(force=false)=>{
 if(running.current)return;running.current=true;setBusy(true);setError('');
 try{let offset=0,remaining=0,failed=false;do{const r=await fetch('/olympiad/api/audience',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'sync',force,offset})});const d=await r.json();if(!r.ok)throw Error(d.error);failed=d.results.some((row:{result:string;pending:boolean})=>row.result==='failed'||row.pending);remaining=d.remaining;offset=d.next_offset??0;if(failed)break;}while(remaining>0);await load();if(mounted.current)setNotice(failed?'Some contacts still need sync. Review the status below, then retry.':force?'Mailchimp groups checked and updated. No campaign email was sent.':'Campaign groups are up to date.');}
 catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Unable to sync Mailchimp.');}
 finally{running.current=false;if(mounted.current)setBusy(false);}
 },[load]);
 useEffect(()=>{mounted.current=true;void sync();const timer=setInterval(()=>void sync(),60000);const reconcile=setInterval(()=>void sync(true),300000);const changed=()=>void sync();window.addEventListener('olympiad-audience-changed',changed);return()=>{mounted.current=false;clearInterval(timer);clearInterval(reconcile);window.removeEventListener('olympiad-audience-changed',changed);};},[sync]);
 return <section><p className={styles.eyebrow}>MAILCHIMP · CAMPAIGN GROUPS</p><h2>The right next step for each captain</h2><p>Team approval, history and roster readiness update Mailchimp tags. Changes queue automatically and sync while this chairman dashboard is open. Use the button to check every captain against Mailchimp again.</p><button disabled={busy} onClick={()=>void sync(true)}>{busy?'Syncing campaign groups…':'Check and sync Mailchimp groups'}</button>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className={styles.inviteList}>{contacts.map(c=><article key={c.email}><strong>{c.email}</strong><p>{label(c.last_result)}{c.pending?' · Update pending':''}</p><p>Website groups: {c.tags.map(t=>t.replace('Olympiad 2027 | ','')).join(' · ')||'No eligible campaign group'}</p>{c.last_synced_at&&<p>Last checked {new Date(c.last_synced_at).toLocaleString()}</p>}{c.last_error&&<p role="alert">{c.last_error}</p>}</article>)}</div><p className={styles.caption}>Only existing subscribed Mailchimp contacts receive campaign groups. Unsubscribed, cleaned and pending contacts are excluded. Registration does not subscribe anyone. Participant subscription sync and automatic campaign sending are not enabled.</p><p>For new-team or welcome-back campaigns, select the matching tag. Exclude the Registered tag from recruitment campaigns. Mixed-history captains are held for manual selection so they do not receive conflicting welcomes.</p></section>;
}
