'use client';
import {useEffect,useState} from 'react';
import styles from './organizer.module.css';
type Row={email:string;email_verified:boolean;last_sign_in_at:string|null;team_count:number;participant_count:number;email_status?:string};
type Report={connected:boolean;notice?:string;updated_at?:string;campaign?:{title:string;status:string;sent_at:string|null;emails_sent:number;bounces:number};invitations:Row[]};
export default function Communications(){
 const [report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');fetch('/olympiad/api/communications',{cache:'no-store',signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok){setReport(null);throw Error(d.error||'Unable to load communication status.');}return d;}).then(setReport).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[revision]);
 const cohort=report?.invitations.filter(i=>i.email_status && i.email_status!=='not_in_campaign')||[];
 return <section id="communications"><p className={styles.eyebrow}>COMMUNICATIONS</p><h2>Early-access invitations</h2><p>Track the invitation and the captain’s actual progress in one place.</p><button disabled={loading} onClick={()=>setRevision(v=>v+1)}>{loading?'Loading invitation progress…':'Refresh invitation progress'}</button>{error&&<p role="alert">{error}</p>}{report?.notice&&<p role="status">{report.notice}</p>}{report?.campaign&&<><p><strong>{report.campaign.title}</strong><br/>Campaign: {report.campaign.status} · {report.campaign.emails_sent} sent · {report.campaign.bounces} bounces reported</p><div className={styles.actionGrid}><p><strong>{cohort.filter(i=>i.last_sign_in_at).length}/{cohort.length}</strong> invited captains signed in</p><p><strong>{cohort.filter(i=>i.team_count>0).length}/{cohort.length}</strong> invited captains created teams</p></div></>}{report&&<div className={styles.inviteList}>{report.invitations.map(i=><article key={i.email}><strong>{i.email}</strong><div><span>Email: {i.email_status==='sent'?'Sent by Mailchimp':i.email_status==='not_in_campaign'?'Not in this campaign':i.email_status||'Status unavailable'}</span><span>{i.last_sign_in_at?'Signed in':i.email_verified?'Email verified':'Awaiting first sign-in'}</span><span>{i.team_count} {i.team_count===1?'team':'teams'} · {i.participant_count} participants saved</span></div></article>)}</div>}<p className={styles.caption}>“Sent” is Mailchimp’s status, not proof the email reached the inbox. Opens and clicks can come from security scanners; signup progress comes from the website. Refresh to update.</p><p><a href="https://us8.admin.mailchimp.com/campaigns" target="_blank" rel="noreferrer">Manage email campaigns in Mailchimp ↗</a></p><p>Next: draft invitations and roster reminders here, preview the exact recipients, then send. Automatic reminders, participant subscription sync and SMS are not enabled.</p></section>;
}
