'use client';
import {useEffect,useState,useCallback,type FormEvent} from 'react';
import styles from './returning.module.css';
type History={year:number;team_name:string;evidence:string;source_url:string;source_sheet:string;source_row:number;note:string};
type SourceContact={name:string;email:string;phone:string;year:number;source_url:string;source_sheet:string;source_row:number};
type Account={id:string;business_name:string;industry:string;aliases:string[];history:History[];source_contacts:SourceContact[];contact_name:string;contact_email:string;contact_phone:string;outreach_status:string;assigned_to:string;notes:string;next_follow_up:string|null;linked_team_id:string|null;version:number};
type Team={id:string;company:string;name:string;approval_status:string};
type Activity={id:string;kind:string;outcome:string;outreach_status:string;created_at:string};
const statuses:Record<string,string>={not_contacted:'Not contacted',attempted:'Attempted contact',follow_up:'Follow up',interested:'Interested',committed:'Committed · signup pending',not_returning:'Not returning',do_not_contact:'Do not contact'};
const norm=(s:string)=>s.toLowerCase().replace(/^the\s+/,'').replace(/[^a-z0-9]/g,'');
const years=(a:Account)=>Array.from(new Set(a.history.map(h=>h.year))).sort((a,b)=>b-a);
const arizonaToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Phoenix',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const isDue=(a:Account,today:string)=>!!a.next_follow_up&&a.next_follow_up<=today&&!['not_returning','do_not_contact'].includes(a.outreach_status)&&!a.linked_team_id;
async function response(r:Response){const data=await r.json();if(!r.ok)throw new Error(data.error||'Please retry.');return data;}
export default function ReturningTeams({teams}:{teams:Team[]}){
 const [accounts,setAccounts]=useState<Account[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[loaded,setLoaded]=useState(false);
 const [search,setSearch]=useState(''),[year,setYear]=useState(''),[industry,setIndustry]=useState(''),[queue,setQueue]=useState('all'),[page,setPage]=useState(0);
 const [dirtyId,setDirtyId]=useState<string|null>(null);const onDirty=useCallback((id:string,dirty:boolean)=>setDirtyId(current=>dirty?id:current===id?null:current),[]);
 const [opened,setOpened]=useState<string|null>(null);const today=arizonaToday();
 async function load(){setLoading(true);setError('');try{const d=await response(await fetch('/olympiad/api/returning-teams',{cache:'no-store'}));setAccounts(d.accounts);setLoaded(true);}catch(e){setAccounts([]);setLoaded(false);setError(e instanceof Error?e.message:'Unable to load.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{setPage(0);},[search,year,industry,queue]);
 const active=teams.filter(t=>t.approval_status!=='declined');
 const visible=accounts.filter(a=>(!year||years(a).includes(Number(year)))&&(!industry||a.industry===industry)&&`${a.business_name} ${a.contact_name} ${a.contact_email} ${a.assigned_to} ${a.aliases.join(' ')}`.toLowerCase().includes(search.toLowerCase())&&(queue==='all'||queue==='due'&&isDue(a,today)||queue==='historical_phone'&&a.source_contacts.some(c=>c.phone)||queue==='missing_phone'&&!a.contact_phone||queue==='missing_email'&&!a.contact_email||queue==='registered'&&!!a.linked_team_id||queue==='review'&&a.history.some(h=>h.evidence==='Needs participation review')||queue==='unlinked'&&!a.linked_team_id||a.outreach_status===queue&&(queue!=='not_contacted'||!a.linked_team_id))).sort((a,b)=>Number(isDue(b,today))-Number(isDue(a,today))||a.business_name.localeCompare(b.business_name));
 const pageCount=Math.max(1,Math.ceil(visible.length/15)),currentPage=Math.min(page,pageCount-1);
 function exportList(){const safe=(s:unknown)=>{let v=String(s??'');if(/^[=+@\-\t\r]/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"';};const rows=[['Business','Industry','Years in source records','Contact','Email','Phone','Outreach status','Owner','Next follow-up','Linked registration','Notes'],...visible.map(a=>[a.business_name,a.industry,years(a).join(' / '),a.contact_name,a.contact_email,a.contact_phone,statuses[a.outreach_status],a.assigned_to,a.next_follow_up,a.linked_team_id?'Yes':'No',a.notes])];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const el=document.createElement('a');el.href=url;el.download='olympiad-returning-teams-'+today+'.csv';el.click();URL.revokeObjectURL(url);}
 return <details id="returning-teams" className={styles.panel}>
  <summary><span><strong>Returning teams · recruitment tracker</strong><small>Past teams, contact details and your next calls</small></span><span>{loaded?`${accounts.length} businesses`:'Loading…'}</span></summary>
  <div className={styles.body}>
   <div className={styles.heading}><div><p className={styles.eyebrow}>BRING THEM BACK FOR 2027</p><h2>Your returning-team call list</h2><p>Find a business. Confirm its captain. Record the conversation and next step.</p></div><button type="button" disabled={loading||!!dirtyId} onClick={load}>{loading?'Loading…':'Reload list'}</button></div>
   {error&&<p role="alert">{error}</p>}
   {loaded&&<>
    <div className={styles.stats}><button disabled={!!dirtyId} onClick={()=>setQueue('all')}><strong>{accounts.length}</strong>Businesses in history</button><button disabled={!!dirtyId} onClick={()=>setQueue('not_contacted')}><strong>{accounts.filter(a=>a.outreach_status==='not_contacted'&&!a.linked_team_id).length}</strong>Not contacted</button><button disabled={!!dirtyId} onClick={()=>setQueue('due')}><strong>{accounts.filter(a=>isDue(a,today)).length}</strong>Follow-ups due</button><button disabled={!!dirtyId} onClick={()=>setQueue('registered')}><strong>{accounts.filter(a=>a.linked_team_id).length}</strong>Linked to 2027 signup</button></div>
    <details className={styles.sourceNote}><summary>About this history & contact quality</summary><p><strong>2026:</strong> final team list and captain records. <strong>2025:</strong> named team rows on the video scoreboard; this list is incomplete, especially residential teams. <strong>2024:</strong> confirmed tracking sheet with 2024 liaison columns; uncertain and dropped-out entries are flagged for review. These are source records, not verified event-day attendance.</p><p>{accounts.filter(a=>a.contact_email).length} businesses have an email; {accounts.filter(a=>a.contact_phone).length} have a primary contact phone. Historical contacts may have changed. Confirm details when calling. Imported contacts have not been enrolled in email or SMS campaigns.</p></details>
    {dirtyId&&<p role="status">Save or discard the open business before changing the call list.</p>}<fieldset disabled={!!dirtyId} className={styles.filters}><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Business, captain, email or owner"/></label><label>Prior year<select value={year} onChange={e=>setYear(e.target.value)}><option value="">All years</option>{[2026,2025,2024].map(y=><option key={y}>{y}</option>)}</select></label><label>Industry<select value={industry} onChange={e=>setIndustry(e.target.value)}><option value="">All categories</option>{Array.from(new Set(accounts.map(a=>a.industry))).sort().map(x=><option key={x}>{x}</option>)}</select></label><label>Call queue<select value={queue} onChange={e=>setQueue(e.target.value)}><option value="all">All businesses</option><option value="due">Follow-ups due</option><option value="unlinked">No linked registration</option><option value="missing_phone">Needs primary phone number</option><option value="historical_phone">Historical phone available</option><option value="missing_email">Needs email address</option><option value="review">Review historical participation</option><option value="registered">Linked to 2027 signup</option>{Object.entries(statuses).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label></fieldset>
    <div className={styles.listHead}><p><strong>{visible.length}</strong> businesses match · Arizona follow-up dates</p><button onClick={exportList} disabled={!visible.length||!!dirtyId}>Export this call list</button></div>
    <div className={styles.list}>{visible.slice(currentPage*15,currentPage*15+15).map(a=><AccountRow key={a.id} account={a} teams={active} today={today} open={opened===a.id} locked={!!dirtyId&&dirtyId!==a.id} onDirty={onDirty} onOpen={v=>setOpened(v?a.id:null)} onSaved={saved=>setAccounts(items=>items.map(x=>x.id===saved.id?saved:x))}/>)}</div>
    {!visible.length&&<p>No businesses match these filters.</p>}
    <div className={styles.pagination}><button disabled={!currentPage||!!dirtyId} onClick={()=>setPage(currentPage-1)}>Previous</button><span>Page {currentPage+1} of {pageCount}</span><button disabled={currentPage>=pageCount-1||!!dirtyId} onClick={()=>setPage(currentPage+1)}>Next</button></div>
   </>}
  </div>
 </details>;
}
function AccountRow({account:a,teams,today,open,locked,onDirty,onOpen,onSaved}:{account:Account;teams:Team[];today:string;open:boolean;locked:boolean;onDirty:(id:string,dirty:boolean)=>void;onOpen:(v:boolean)=>void;onSaved:(a:Account)=>void}){
 const [draft,setDraft]=useState(a),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[kind,setKind]=useState(''),[outcome,setOutcome]=useState(''),[activities,setActivities]=useState<Activity[]>([]),[activityError,setActivityError]=useState('');
 useEffect(()=>{onDirty(a.id,dirty);},[a.id,dirty,onDirty]);
 useEffect(()=>{if(!dirty)setDraft(a);},[a,dirty]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>{if(!open)return;const controller=new AbortController();setActivityError('');fetch('/olympiad/api/returning-teams?account_id='+a.id,{cache:'no-store',signal:controller.signal}).then(response).then(d=>setActivities(d.activities)).catch(e=>{if(e.name!=='AbortError')setActivityError('Unable to load previous activity.');});return()=>controller.abort();},[a.id,a.version,open]);
 const matches=teams.filter(t=>a.aliases.concat(a.business_name).some(n=>norm(n)===norm(t.company)||norm(n)===norm(t.name)));
 function change(key:keyof Account,value:string){setDraft(d=>({...d,[key]:value}));setDirty(true);setNotice('');}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{const d=await response(await fetch('/olympiad/api/returning-teams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,id:a.id,version:a.version,activity_kind:kind,activity_outcome:outcome})}));onSaved(d.account);setDraft(d.account);setDirty(false);setKind('');setOutcome('');setNotice('Saved.');}catch(e){setError(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 return <details className={styles.row} open={open} onToggle={e=>{if(e.currentTarget.open!==open)onOpen(e.currentTarget.open);}}>
  <summary onClick={e=>{if(locked)e.preventDefault();}}><span><strong>{a.business_name}</strong><small>{a.industry} · {years(a).join(' / ')}</small><small>{a.contact_name||'Captain name needed'}{dirty?' · Unsaved changes':''}</small>{a.history.some(h=>h.evidence==='Needs participation review')&&<small>Historical participation needs review</small>}</span><span>{a.linked_team_id?'2027 signup linked':statuses[a.outreach_status]}<small>{isDue(a,today)?'Follow-up due':a.next_follow_up?'Next: '+a.next_follow_up:a.contact_phone?'Phone on file':a.source_contacts.some(c=>c.phone)?'Historical phone · review contact':'Add phone number'}</small></span><span className={styles.drill}>{open?'Close −':'Open +'}</span></summary>
  {open&&<div className={styles.detail}>
   <div className={styles.quickActions}>{a.outreach_status==='do_not_contact'?<strong>Do not contact · outreach paused</strong>:<>{a.contact_phone&&<a href={'tel:'+a.contact_phone.replace(/[^+0-9]/g,'')}>Call {a.contact_phone}</a>}{a.contact_email&&<a href={'mailto:'+a.contact_email}>Email {a.contact_email}</a>}</>}</div>
   {!!matches.length&&!a.linked_team_id&&<p className={styles.notice}><strong>Possible 2027 match:</strong> {matches.map(t=>t.company+' ('+t.name+')').join(', ')}. Confirm the correct registration below.</p>}
   <form onSubmit={save} className={styles.form}>
    <fieldset disabled={busy}><legend>Contact & next step</legend><div className={styles.fields}>
     <label>Captain / contact name<input value={draft.contact_name} maxLength={250} onChange={e=>change('contact_name',e.target.value)} autoComplete="off"/></label>
     <label>Email<input type="email" value={draft.contact_email} maxLength={320} onChange={e=>change('contact_email',e.target.value)} autoComplete="off"/></label>
     <label>Phone<input type="tel" value={draft.contact_phone} maxLength={60} onChange={e=>change('contact_phone',e.target.value)} placeholder="Add a number for your call list" autoComplete="off"/></label>
     <label>Outreach owner / liaison<input value={draft.assigned_to} maxLength={250} onChange={e=>change('assigned_to',e.target.value)}/></label>
     <label>Outreach status<select value={draft.outreach_status} onChange={e=>change('outreach_status',e.target.value)}>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
     <label>Next follow-up<input type="date" value={draft.next_follow_up||''} onChange={e=>change('next_follow_up',e.target.value)}/></label>
     <label className={styles.full}>Link actual 2027 registration<select value={draft.linked_team_id||''} onChange={e=>change('linked_team_id',e.target.value)}><option value="">No confirmed registration link</option>{teams.map(t=><option key={t.id} value={t.id}>{t.company} · {t.name} · {t.approval_status}</option>)}</select></label>
     <label className={styles.full}>Working notes<textarea value={draft.notes} maxLength={10000} rows={3} onChange={e=>change('notes',e.target.value)} placeholder="Current contact, objections, interests or next steps"/></label>
    </div></fieldset>
    <fieldset disabled={busy}><legend>Log a conversation (optional)</legend><div className={styles.fields}><label>Activity<select value={kind} onChange={e=>{setKind(e.target.value);setDirty(true);}}><option value="">No new activity</option>{['call','email','text','meeting','note'].map(v=><option key={v}>{v}</option>)}</select></label><label>Outcome<input value={outcome} maxLength={2000} required={!!kind} onChange={e=>{setOutcome(e.target.value);setDirty(true);}} placeholder="Left voicemail; interested; new captain…"/></label></div><p>Records an activity you completed. This form does not send a message.</p></fieldset>
    <div className={styles.save}><button disabled={busy||!dirty}>{busy?'Saving…':'Save contact & follow-up'}</button>{dirty&&<><small>Unsaved changes</small><button type="button" disabled={busy} onClick={()=>{setDraft(a);setDirty(false);setKind('');setOutcome('');setError('');setNotice('Changes discarded.');}}>Discard changes</button></>}{notice&&<span role="status">{notice}</span>}</div>{error&&<p role="alert">{error}</p>}
   </form>
   <details className={styles.history}><summary>Participation records & historical contacts</summary><p>Review these sources before assuming attendance or using an older contact.</p><ul>{a.history.map((h,i)=><li key={i}><strong>{h.year} · {h.team_name}</strong><span>{h.evidence} · <a href={h.source_url} target="_blank" rel="noopener noreferrer">{h.source_sheet}, row {h.source_row}</a></span>{h.note&&<small>{h.note}</small>}</li>)}</ul><h4>Contacts from source records</h4><ul>{a.source_contacts.map((c,i)=><li key={i}><strong>{c.name||'Name not recorded'} · {c.year}</strong><span>{c.email||'Email not recorded'}{c.phone?' · '+c.phone:''} · <a href={c.source_url} target="_blank" rel="noopener noreferrer">{c.source_row?'Source row '+c.source_row:c.source_sheet}</a></span><button type="button" onClick={()=>{setDraft(d=>({...d,contact_name:c.name,contact_email:c.email,contact_phone:c.phone}));setDirty(true);setNotice('');}}>Use this contact</button></li>)}</ul></details>
   <div className={styles.history}><h4>Recent outreach · latest 50</h4>{activityError&&<p role="alert">{activityError}</p>}{!activities.length&&!activityError&&<p>No conversations logged yet.</p>}<ul>{activities.map(x=><li key={x.id}><strong>{x.kind} · {new Date(x.created_at).toLocaleString('en-US',{timeZone:'America/Phoenix'})}</strong><span>{x.outcome}</span><small>{statuses[x.outreach_status]||x.outreach_status}</small></li>)}</ul></div>
  </div>}
 </details>;
}
