'use client';
import {useState} from 'react';
import styles from './season.module.css';
type Props={approved:number;active:number;ready:number;due:number;pending:number;fundraisingActive:boolean;onQueue:(queue:'pending'|'due'|'roster')=>void};
const phases=[
 {id:'prepare',window:'Now–Nov 2026',title:'Prepare',audience:'Internal members + early-access captains',purpose:'Make joining easy before inviting the wider community.',tasks:['Gather pilot feedback and resolve signup friction','Confirm date, venue, inclusions and 2027 fundraising options','Assign industry liaisons and build a prospect list'],email:'Personal early-access welcome + feedback follow-up',social:'Collect real team photos, game clips and captain stories.',cta:'See what Olympiad is all about',campaigns:[]},
 {id:'recruit',window:'Dec 2026–Jan 2027',title:'Invite',audience:'Business owners, team leads and returning captains',purpose:'Make the event easy to understand and the fundraising goal feel achievable.',tasks:['Reconnect with returning businesses personally','Explain what is included, the six-person minimum and a practical path to $3,000','Ask club members and captains to invite a friendly rival'],email:'New-team introduction, welcome back and how it works',social:'Team building, community impact and reconnecting with friends at other businesses.',cta:'Explore Olympiad · Share with your team',campaigns:[['7250186','New-team introduction'],['7250188','Welcome back'],['7250189','How it works']]},
 {id:'activate',window:'Feb 2027',title:'Get teams ready',audience:'Interested businesses + registered captains',purpose:'Replace uncertainty with one clear next step for each captain.',tasks:['Review registrations and possible duplicate businesses','Follow up on missing roster and shirt details','Help each captain choose a practical fundraising plan'],email:'Roster reminder, signup help and the first $3,000 plan',social:'Meet participating businesses; show an easy next step.',cta:'Start your team · Update your roster',campaigns:[['7250191','Roster reminder'],['7250192','First $3,000 plan'],['7250193','Signup help']]},
 {id:'raise',window:'Mar–Apr 2027',title:'Build momentum',audience:'Approved captains + permissioned participants',purpose:'Keep fundraising visible and help teams close the gap.',tasks:['Confirm transaction credit and resolve missing purchases','Contact teams below minimum with one specific next step','Recognize progress and agree stretch goals with ready teams'],email:'A specific fundraising ask, standings and a focused final push',social:'Industry rivalries, team milestones and charity impact.',cta:'See fundraising options · Check your progress',campaigns:[['7250194','Make your next ask specific'],['7250195','Progress and milestones'],['7250196','Close the gap']]},
 {id:'event',window:'Confirmed event week',title:'Game day',audience:'Captains + participants',purpose:'Deliver a well-paced day that people want to repeat.',tasks:['Confirm arrival, parking, game schedule and weather plan','Publish clear updates and reduce waits between games','Capture team photos, cup winners and game medal winners'],email:'Final team guide + essential event updates',social:'On-field moments, friendly competition and celebrations.',cta:'Read the team guide',campaigns:[['7250197','Before game day']]},
 {id:'return',window:'After the event',title:'Bring them back',audience:'Participating businesses + captains + supporters',purpose:'Turn one great day into an annual company tradition.',tasks:['Thank teams and share verified charitable impact','Send photos and a short feedback survey','Invite captains to return with their business and reconnect with friendly rivals'],email:'Thank-you, results, photos and a return invitation',social:'Celebrate the people and the impact, then share the memories.',cta:'See your team photos · Stay in the loop',campaigns:[]}
];
export default function SeasonOverview(p:Props){
 const [selected,setSelected]=useState('prepare');const phase=phases.find(x=>x.id===selected)!;
 return <section className={styles.overview} aria-labelledby="season-title">
  <div className={styles.top}><div><p className={styles.eyebrow}>THE ROAD TO OLYMPIAD 2027</p><h2 id="season-title">Build the audience. Bring them back.</h2><p>A season view of the people, tasks and messages that move teams forward.</p></div><div className={styles.goal}><strong>{p.approved} / 150+</strong><span>approved teams · season goal</span><progress value={Math.min(150,p.approved)} max={150} aria-label={`${p.approved} approved teams toward a goal of at least 150`}/></div></div>
  <div className={styles.pulse} aria-label="Current audience pulse"><div><strong>{p.active}</strong><span>active registrations</span></div><button onClick={()=>p.onQueue('pending')}><strong>{p.pending}</strong><span>awaiting approval ↗</span></button><button onClick={()=>p.onQueue('roster')}><strong>{Math.max(0,p.active-p.ready)}</strong><span>need roster help ↗</span></button><button onClick={()=>p.onQueue('due')}><strong>{p.due}</strong><span>follow-ups due ↗</span></button></div>
  <p className={styles.caption}>Live registration counts from this overview, including active pilot records. Interested prospects and year-over-year return rates are not tracked yet.</p>
  <nav className={styles.timeline} aria-label="Choose a season phase">{phases.map((x,i)=><button key={x.id} aria-pressed={selected===x.id} aria-controls="season-detail" className={selected===x.id?styles.selected:''} onClick={()=>setSelected(x.id)}><span className={styles.number}>{i+1}</span><strong>{x.title}</strong><small>{x.window}</small></button>)}</nav>
  <div id="season-detail" className={styles.detail}><div className={styles.focus}><p className={styles.eyebrow}>{phase.window} · PROPOSED PLAN</p><h3>{phase.purpose}</h3><p><strong>Who we’re reaching</strong><br/>{phase.audience}</p><p className={styles.cta}><strong>Invitation to take the next step</strong><br/>{phase.cta}</p></div><div><h3>Tasks to coordinate</h3><ul className={styles.tasks}>{phase.tasks.map(task=><li key={task}><span aria-hidden="true">○</span>{task}</li>)}</ul><p className={styles.caption}>Chairman + assigned liaisons. These are planning prompts; per-team owners, notes and follow-up dates are saved in the team list below.</p></div><div className={styles.messages}><h3>Keep the conversation going</h3><p><span className={styles.label}>EMAIL</span>{phase.email}</p><p><span className={styles.label}>SOCIAL</span>{phase.social}</p>{phase.campaigns.length>0&&<details><summary>Review {phase.campaigns.length} email drafts</summary><ul>{phase.campaigns.map(([id,title])=><li key={id}><a href={`https://us8.admin.mailchimp.com/campaigns/edit?id=${id}`} target="_blank" rel="noreferrer">{title} ↗</a></li>)}</ul><p className={styles.caption}>Draft links, not a send schedule. Check current campaign status in Mailchimp.</p></details>}</div></div>
  {selected==='raise'&&!p.fundraisingActive&&<p className={styles.notice}>Before this phase: enable and reconcile fundraising credit. Current standings must use real transactions before progress campaigns are released.</p>}
  {selected==='event'&&<p className={styles.notice}>Event date and 2027 logistics need confirmation before game-day messages are released.</p>}
  <div className={styles.bottom}><a href="#communications">View invitation progress ↓</a><a href="#team-actions">Work through team action items ↓</a><span>Planning windows · select a phase to explore</span></div>
 </section>;
}
