const test=require('node:test'),assert=require('node:assert/strict'),ts=require('typescript'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const base=path.resolve(__dirname,'../src/app/olympiad');
function load(file,mocks={}) {const exports={};const code=ts.transpileModule(fs.readFileSync(path.join(base,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{exports,require:n=>{if(n in mocks)return mocks[n];throw Error(n);},Buffer,File,Blob,Response,Request,URL,crypto,console});return exports;}
const id='11111111-1111-4111-8111-111111111111',object=id+'/33333333-3333-4333-8333-333333333333.ai';
function fixture({signedIn=true,owner='captain',bytes=Buffer.from('%PDF-test'),storageError=false,metadataError=false}={}) {
 const writes=[];const storage={createSignedUploadUrl:async p=>({data:{signedUrl:'https://storage.example.test/'+p}}),download:async()=>storageError?{error:{}}:{data:new Blob([bytes])},upload:async()=>({}),createSignedUrl:async()=>({data:{signedUrl:'https://storage.example.test/private?download=logo.ai'}})};
 const client={auth:{getUser:async()=>({data:{user:signedIn?{id:'captain',email_confirmed_at:'yes'}:null}})},storage:{from:()=>storage},from:table=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:table==='teams'?{captain_user_id:owner}:{object_path:object,filename:'logo.ai'}})})}),upsert:async asset=>{writes.push({table,asset});return {error:metadataError?{}:null};}})};
 const route=load('api/logo/route.ts',{'next/server':{NextResponse:{json:(b,o)=>Response.json(b,o)}},'../../pilot/server':{allowedOrigin:r=>r.headers.get('origin')==='https://site.example.test',pilotClient:async()=>client},'../../auth/chairman-access':{chairmanAccess:async()=>({ok:false,status:403})},'../../pilot/validation':load('pilot/validation.ts')});
 return {route,writes,request:(body,origin='https://site.example.test')=>new Request('https://site.example.test/olympiad/api/logo',{method:'POST',headers:{'Content-Type':'application/json',origin},body:JSON.stringify({team_id:id,filename:'logo.ai',...body})})};
}
test('upload preparation requires origin, confirmed login and exact team ownership',async()=>{for(const [opts,origin,status] of [[{},'https://evil.test',403],[{signedIn:false},undefined,401],[{owner:'other'},undefined,403]]){const f=fixture(opts);assert.equal((await f.route.POST(f.request({action:'prepare',size:7e6},origin))).status,status);}});
test('7 MB AI accepted; oversized vectors and web images rejected',async()=>{const f=fixture();for(const [body,status] of [[{size:7*1024*1024},200],[{size:21*1024*1024},400],[{filename:'logo.png',size:5*1024*1024},400]])assert.equal((await f.route.POST(f.request({action:'prepare',...body}))).status,status);assert.equal(f.writes.length,0);});
test('7 MB vector validated and attached without replacing website image',async()=>{const bytes=Buffer.alloc(7*1024*1024);bytes.write('%PDF-');const f=fixture({bytes});const r=await f.route.POST(f.request({action:'complete',path:object}));assert.equal(r.status,200);assert.equal((await r.json()).logo.size_bytes,bytes.length);assert.equal(f.writes.length,1);assert.equal(f.writes[0].table,'team_brand_assets');});
test('bad path, corrupt or oversized bytes, and missing storage object leave metadata unchanged',async()=>{for(const opts of [{bytes:Buffer.from('bad')},{bytes:Buffer.alloc(21*1024*1024)},{storageError:true}]){const f=fixture(opts);assert.ok((await f.route.POST(f.request({action:'complete',path:object}))).status>=400);assert.equal(f.writes.length,0);}const f=fixture();assert.equal((await f.route.POST(f.request({action:'complete',path:'../other-team/logo.ai'}))).status,400);assert.equal(f.writes.length,0);});
test('metadata errors surfaced and authorized download redirects around host response limit',async()=>{const f=fixture({metadataError:true});assert.equal((await f.route.POST(f.request({action:'complete',path:object}))).status,503);const r=await fixture().route.GET(new Request('https://site.example.test/olympiad/api/logo?team_id='+id));assert.equal(r.status,302);assert.match(r.headers.get('location'),/^https:\/\/storage\.example\.test/);assert.equal(r.headers.get('cache-control'),'private, no-store');});
