begin;
create temp table smoke_context as select t.id team_id,t.captain_user_id,t.roster_version,encode(extensions.gen_random_bytes(32),'hex') token from public.teams t join public.event_editions e on e.id=t.event_id where e.year=2027 and t.status='registered' and not exists(select 1 from public.team_reviews r where r.team_id=t.id and r.status='declined') limit 1;
insert into olympiad_private.roster_links(team_id,token,expires_at,created_by) select team_id,token,now()+interval '1 hour',captain_user_id from smoke_context on conflict(team_id) do update set token=excluded.token,expires_at=excluded.expires_at,revoked_at=null,window_attempts=0;
create temp table smoke_results(check_name text,result jsonb);
grant select on smoke_context to anon,authenticated; grant insert,select on smoke_results to anon,authenticated;
set local role anon;
insert into smoke_results select 'public_header',public.roster_link_details(token) from smoke_context;
insert into smoke_results select 'missing_last_name',public.join_team_roster(token,'Smoke','','roster-smoke@example.invalid','2025550100','M','male',true,false,false) from smoke_context;
insert into smoke_results select 'valid_join',public.join_team_roster(token,'Smoke','Test','roster-smoke@example.invalid','2025550100','M','male',true,true,false) from smoke_context;
insert into smoke_results select 'duplicate',public.join_team_roster(token,'Smoke','Test','roster-smoke@example.invalid','2025550100','M','male',true,true,false) from smoke_context;
reset role;
select set_config('request.jwt.claim.sub',captain_user_id::text,true) from smoke_context;
set local role authenticated;
insert into smoke_results select 'captain_read',jsonb_build_object('count',count(*)) from public.roster_participants p join smoke_context c on p.team_id=c.team_id where p.email='roster-smoke@example.invalid';
insert into smoke_results select 'captain_preferences',jsonb_build_object('count',count(*)) from public.roster_contact_preferences where submitted_email='roster-smoke@example.invalid';
do $$ declare c record; begin select * into c from smoke_context; begin perform public.save_roster(c.team_id,'[]'::jsonb,c.roster_version); raise exception 'FAILED stale save allowed'; exception when others then if sqlerrm<>'Roster changed. Reload before saving.' then raise; end if; insert into smoke_results values('stale_save_rejected','{"ok":true}'); end; end $$;
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',u.id,'email',u.email,'role','authenticated','amr',jsonb_build_array(jsonb_build_object('method','oauth')),'session_id',s.id)::text,true) from auth.users u join public.organizer_memberships m on m.user_id=u.id join auth.sessions s on s.user_id=u.id where exists(select 1 from auth.mfa_amr_claims c where c.session_id=s.id and c.authentication_method='oauth') and not exists(select 1 from auth.mfa_amr_claims c where c.session_id=s.id and c.authentication_method not in ('oauth','token_refresh','totp')) order by s.created_at desc limit 1;
set local role authenticated;
insert into smoke_results select 'chairman_read',jsonb_build_object('count',count(*)) from public.roster_participants p join smoke_context c on p.team_id=c.team_id where p.email='roster-smoke@example.invalid';
reset role;
select set_config('request.jwt.claims','{}',true); select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',true);
set local role authenticated;
insert into smoke_results select 'unrelated_read',jsonb_build_object('count',count(*)) from public.roster_contact_preferences where submitted_email='roster-smoke@example.invalid';
reset role;
update olympiad_private.roster_links set revoked_at=now() where team_id=(select team_id from smoke_context);
set local role anon;
insert into smoke_results select 'revoked_link',public.join_team_roster(token,'Smoke','Test','roster-smoke2@example.invalid','2025550100','M','male',true,false,false) from smoke_context;
reset role;
select * from smoke_results; rollback;
