'use client';
import {useState} from 'react';
import s from './pilot.module.css';
export default function RosterLink({teamId,teamName,captainName,disabled,onRefresh}:{teamId:string;teamName:string;captainName?:string;disabled?:boolean;onRefresh:()=>void}){
 const [url,setUrl]=useState(''),[expires,setExpires]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const text=`${captainName||'Your captain'} is inviting you to join ${teamName} at Olympiad 2027. Add your contact details and shirt size—about a minute, no account needed.\n${url}`;
 async function manage(action:string){setBusy(true);setError('');setMessage('');try{const response=await fetch('/olympiad/api/roster-link',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,team_id:teamId})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to prepare your roster link.');setUrl(data.url||'');setExpires(data.expires_at||'');setMessage(action==='revoke'?'Roster link disabled. Previously saved participants are unchanged.':action==='rotate'?'New link ready. The previous link no longer works.':'Your link is ready to share.');}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 return <section className={s.rosterShare} aria-label="Invite teammates to your roster"><span className={s.eyebrow}>LESS CHASING. MORE TEAMWORK.</span><h3>Let teammates fill in their own details.</h3><p className={s.fine}>Send one link in your group chat. Teammates add their name, email, phone and shirt size and fit directly to your private roster. No sign-in needed.</p>
 {!url?<button type="button" className={s.primary} disabled={busy||disabled} onClick={()=>void manage('get')}>{busy?'Preparing link…':'Share roster link'}</button>:<><label className={s.field}>Your team’s roster link<input readOnly value={url} aria-label="Your team’s roster link" onFocus={e=>e.target.select()}/></label><div className={s.actions}><button type="button" className={s.primary} disabled={busy} onClick={async()=>{try{await navigator.clipboard.writeText(text);setMessage('Invitation copied. Paste it into your team group chat.');}catch{setMessage('Select and copy the link above to share it with your team.');}}}>Copy invitation</button><button type="button" className={s.secondary} disabled={busy} onClick={async()=>{try{if(navigator.share){await navigator.share({title:`Join ${teamName}`,text:text.split('\n')[0],url});setMessage('Invitation shared.');}else{await navigator.clipboard.writeText(text);setMessage('Invitation copied. Paste it into your group chat.');}}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setMessage('Use Copy invitation or select the link above.');}}}>Share…</button><button type="button" className={s.secondary} disabled={busy||disabled} onClick={onRefresh}>Refresh roster</button></div><p className={s.fine}>Link expires {new Date(expires).toLocaleDateString()}. Anyone with the link can add their own details; teammates’ contact information is never shown.</p><details><summary>Manage this link</summary><div className={s.actions}><button type="button" disabled={busy} className={s.secondary} onClick={()=>{if(window.confirm('Create a new roster link? The previous link will stop working. Existing participants will stay saved.'))void manage('rotate');}}>Reset link</button><button type="button" disabled={busy} className={s.secondary} onClick={()=>{if(window.confirm('Disable this roster link? Existing participants will stay saved.'))void manage('revoke');}}>Disable link</button></div></details></>}
 {error&&<p className={s.error} role="alert">{error}</p>}{message&&<p className={s.fine} role="status">{message}</p>}<p className={s.fine}>After teammates join, use Refresh roster to see the latest details. Link submissions do not send campaigns automatically.</p></section>;
}
