'use client';
import {useState} from 'react';
import styles from './organizer.module.css';
export default function ChairmanRosterLink({teamId,teamName,captainName,captainEmail,onAccessDenied}:{teamId:string;teamName:string;captainName:string;captainEmail?:string;onAccessDenied:()=>void}){
 const [url,setUrl]=useState(''),[expires,setExpires]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const teammateMessage=`${captainName||'Your captain'} is inviting you to join ${teamName} at Olympiad 2027. Add your first and last name, email, phone, shirt size and fit—about a minute, no sign-in needed.\n${url}`;
 const captainMessage=`Hi ${captainName||'there'}, here’s the roster link for ${teamName}. Please forward the message below to your team or paste it into your group chat. Each teammate can add their own details and shirt preferences without signing in.\n\n${teammateMessage}\n\nThanks for helping us get your team ready!\nSean · Olympiad 2027`;
 async function load(){setBusy(true);setError('');setNotice('');setUrl('');try{const r=await fetch('/olympiad/api/roster-link',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'chairman-get',team_id:teamId})});const d=await r.json();if(!r.ok){if([401,403].includes(r.status)){onAccessDenied();return;}throw Error(d.error||'Unable to retrieve this roster link.');}setUrl(d.url);setExpires(d.expires_at);setNotice('Roster link ready. No message sent.');}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{setBusy(false);}}
 async function copy(value:string,label:string){try{await navigator.clipboard.writeText(value);setNotice(label+' copied.');}catch{setError('Select and copy the link or message below.');}}
 return <section className={styles.rosterLink} aria-label={`Roster sharing for ${teamName}`}><h3>Roster link · send to the captain</h3><p>Help the captain gather <strong>names, email, phone and shirt preferences</strong>. Teammates can fill out the form without a website account.</p><button type="button" disabled={busy} onClick={load}>{busy?'Getting link…':url?'Refresh roster link':'Get team roster link'}</button>{url&&<><label>Team roster URL<input readOnly value={url} onFocus={e=>e.target.select()}/></label><div className={styles.rosterLinkActions}><button type="button" disabled={busy} onClick={()=>copy(url,'Roster URL')}>Copy URL</button><button type="button" disabled={busy} onClick={()=>copy(captainMessage,'Message for captain')}>Copy captain message</button>{captainEmail&&<a href={'mailto:'+encodeURIComponent(captainEmail)+'?subject='+encodeURIComponent(`${teamName} · your Olympiad roster link`)+ '&body='+encodeURIComponent(captainMessage)}>Email draft to captain</a>}</div><details><summary>Preview message to captain</summary><textarea readOnly rows={8} value={captainMessage} aria-label="Message to captain" onFocus={e=>e.target.select()}/></details><p>Uses the same link as the captain’s hub. Expires {new Date(expires).toLocaleDateString()}. Anyone with the link can submit their own details; it does not display the saved roster.</p></>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</section>;
}
